name: Test Deployment
on: 
    workflow_dispatch:
jobs:
    build:
        name: Test Build
        runs-on: [ ubuntu-latest ]
        steps:
            - name: CheckOut
              uses: actions/checkout@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Docker Login
              uses: docker/login-action@v2
              with:
                username: ${{ vars.DOCKER_USERNAME }} 
                password: ${{ secrets.DOCKER_PASSWD }}

            - name: Docker Build and Push
              id: docker-build
              uses: docker/build-push-action@v4
              with:
                context: ./
                file: ./Dockerfile
                tag: ${{ vars.DOCKER_REPO }}:${{github.sha}}

            - name: Deploy to remote server
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.REMOTE_SERVER_HOST }}
                username: ${{ secrets.REMOTE_SERVER_USERNAME }}
                passphrase: ${{ secrets.PASS_PHRASE }}
                key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
                script: |
                   docker pull ${{ vars.DOCKER_REPO }}:${{github.sha}}
                   docker run -d -p 3000:3000 ${{ vars.DOCKER_REPO }}:${{github.sha}}
